#!/usr/bin/env python3
"""
Create screenshots for Zig examples.
This script helps automate the process of taking screenshots of Excel files
generated by Zig implementations, comparing them with C implementations.
After verification, Zig-generated Excel files are moved to a dedicated directory.
"""

import os
import sys
import subprocess
import time
import shutil
from pathlib import Path
import argparse
from PIL import Image


def load_examples(filename):
    """Load examples from a file into a set."""
    try:
        with open(filename, 'r') as f:
            # Strip whitespace and filter out empty lines
            return {line.strip() for line in f if line.strip()}
    except FileNotFoundError:
        print(f"Error: {filename} not found.")
        return set()


def check_screenshot_exists(example_name):
    """Check if a screenshot exists for the Zig implementation."""
    root_dir = Path(__file__).parent.parent
    screenshots_dir = root_dir / "testing" / "screenshots"
    
    # Handle special case for conditional_format1
    screenshot_name = example_name
    if example_name == "conditional_format1":
        screenshot_name = "conditional_format_simple"
    
    # Check for combined screenshot
    screenshot_file = screenshots_dir / f"comparison_{screenshot_name}.png"
    
    return screenshot_file.exists()


def find_examples_without_screenshots():
    """Find examples that don't have Zig screenshots."""
    root_dir = Path(__file__).parent.parent
    
    # Load done and todo examples
    done_examples = load_examples(root_dir / "done.txt")
    todo_examples = load_examples(root_dir / "todo.txt")
    
    all_examples = sorted(done_examples.union(todo_examples))
    missing_screenshots = []
    
    for example in all_examples:
        if not check_screenshot_exists(example):
            missing_screenshots.append(example)
    
    return missing_screenshots


def build_example(example_name):
    """Build the Zig example."""
    root_dir = Path(__file__).parent.parent
    
    # Build Zig example
    cmd = ["zig", "build", example_name]
    try:
        subprocess.run(cmd, cwd=root_dir, check=True)
        return True
    except subprocess.CalledProcessError:
        print(f"Error building Zig example: {example_name}")
        return False


def get_c_excel_file(example_name):
    """Get the path to the C Excel file."""
    root_dir = Path(__file__).parent.parent
    c_output_dir = root_dir / "testing" / "c-output-xls"
    
    # Handle special case for conditional_format1
    c_file_name = example_name
    if example_name == "conditional_format1":
        c_file_name = "conditional_format_simple"
    
    # Handle special case for dates_and_times examples
    if example_name.startswith("dates_and_times"):
        c_file_name = example_name.replace("dates_and_times", "date_and_times")
    
    # Handle special case for macro example which uses .xlsm
    extension = ".xlsm" if example_name == "macro" else ".xlsx"
    
    c_excel_file = c_output_dir / f"{c_file_name}{extension}"
    
    if not c_excel_file.exists():
        print(f"C Excel file not found: {c_excel_file}")
        return None
    
    return c_excel_file


def cleanup_excel_file(example_name, zig_excel_file):
    """
    Move the Zig-generated Excel file to the zig-output-xls directory.
    
    Args:
        example_name: The name of the example
        zig_excel_file: Path to the Zig-generated Excel file
    
    Returns:
        bool: True if the file was moved successfully, False otherwise
    """
    root_dir = Path(__file__).parent.parent
    zig_output_dir = root_dir / "testing" / "zig-output-xls"
    
    # Create the directory if it doesn't exist
    zig_output_dir.mkdir(parents=True, exist_ok=True)
    
    # Special case for macro example which uses .xlsm
    extension = ".xlsm" if example_name == "macro" else ".xlsx"
    
    # Destination path 
    dest_file = zig_output_dir / f"{example_name}{extension}"
    
    try:
        # Move the file
        shutil.move(str(zig_excel_file), str(dest_file))
        print(f"✅ Moved Excel file to: {dest_file}")
        return True
    except Exception as e:
        print(f"❌ Error moving Excel file: {e}")
        return False


def process_screenshot(screenshot_file, top_crop=25, bottom_crop=30):
    """Post-process screenshot to crop pixels from top and bottom.
    Crops 25px from top (Excel title bar) and 30px from bottom (Excel status bar)."""
    try:
        with Image.open(screenshot_file) as img:
            width, height = img.size
            cropped = img.crop((0, top_crop, width, height - bottom_crop))
            cropped.save(screenshot_file)
            return True
    except Exception as e:
        print(f"Error processing screenshot: {e}")
        return False


def take_screenshot(example_name):
    """
    Take a screenshot of both C and Zig Excel files side by side.
    
    This function:
    1. Builds the Zig example
    2. Positions both C and Zig Excel files side by side using excel-position.sh
    3. Takes a screenshot using the macOS screencapture utility
    4. Opens the screenshot for the user to view
    5. Asks the user if the outputs match
    6. If they match, moves the Zig Excel file to the zig-output-xls directory
    """
    if sys.platform != "darwin":
        print("This script currently only supports macOS for automatic screenshots.")
        return False
    
    root_dir = Path(__file__).parent.parent
    screenshots_dir = root_dir / "testing" / "screenshots"
    comparison_dir = root_dir / "testing" / "comparison_results"
    
    # Create directories if they don't exist
    screenshots_dir.mkdir(parents=True, exist_ok=True)
    comparison_dir.mkdir(parents=True, exist_ok=True)
    
    # Handle special case for conditional_format1
    screenshot_name = example_name
    if example_name == "conditional_format1":
        screenshot_name = "conditional_format_simple"
    
    # Determine the screenshot filename
    screenshot_file = screenshots_dir / f"comparison_{screenshot_name}.png"
    
    # Build the example
    if not build_example(example_name):
        return False
    
    # Get the C Excel file
    c_excel_file = get_c_excel_file(example_name)
    if not c_excel_file:
        return False
    
    # Determine the Zig Excel file path
    extension = ".xlsm" if example_name == "macro" else ".xlsx"
    zig_excel_file = root_dir / f"zig-{example_name}{extension}"
    
    if not zig_excel_file.exists():
        print(f"Zig Excel file not found: {zig_excel_file}")
        return False
    
    # Position Excel files side by side
    excel_position_script = root_dir / "utils" / "excel-position.sh"
    
    print(f"\nPositioning Excel files side by side...")
    try:
        subprocess.run([
            str(excel_position_script),
            str(c_excel_file),
            str(zig_excel_file)
        ], check=True)
    except subprocess.CalledProcessError as e:
        print(f"Error positioning Excel files: {e}")
        return False
    
    # Give Excel time to position windows
    print("Waiting for Excel to position windows...")
    time.sleep(3)
    
    # Take screenshot using screencapture
    print(f"Taking screenshot and saving to: {screenshot_file}")
    try:
        subprocess.run([
            "screencapture",
            "-o",  # Capture window contents only
            "-x",  # No sound
            str(screenshot_file)
        ], check=True)
        
        # Post-process the screenshot
        if process_screenshot(screenshot_file):
            print("Screenshot processed successfully")
        else:
            print("Warning: Failed to process screenshot")
            
    except subprocess.CalledProcessError as e:
        print(f"Error taking screenshot: {e}")
        return False
    
    # Check if the screenshot was saved
    if screenshot_file.exists():
        print(f"Screenshot saved: {screenshot_file}")
        
        # Open the screenshot for the user to view
        print("\nOpening screenshot for review...")
        try:
            # Open the screenshot with Preview
            subprocess.run([
                "open", 
                "-a", "Preview", 
                str(screenshot_file)
            ], check=True)
            
            # Give the user time to view the screenshot
            print("Screenshot opened in Preview. Press Enter when ready to continue...")
            input()
            
            # Close Preview
            exit_script = """
            tell application "Preview"
                quit
            end tell
            """
            subprocess.run(["osascript", "-e", exit_script], check=True)
            
        except subprocess.CalledProcessError as e:
            print(f"Error opening screenshot: {e}")
            # Continue anyway, as this is not critical
        
        # Ask user if outputs match
        print("\n=== VISUAL COMPARISON ===")
        print("Do the C and Zig outputs match? (y/n)")
        user_input = input("Enter y or n: ").lower()
        
        # Save comparison result
        result_file = comparison_dir / f"{example_name}_output.txt"
        with open(result_file, 'w') as f:
            f.write(f"Comparison of {example_name} screenshots:\n")
            f.write(f"C Excel file: {c_excel_file}\n")
            f.write(f"Zig Excel file: {zig_excel_file}\n")
            f.write(f"Screenshot: {screenshot_file}\n\n")
            
            if user_input == 'y':
                f.write("RESULT: MATCH - User confirmed visual match\n")
                print("✅ Visual match confirmed.")
                
                # Move the Zig Excel file to the output directory
                cleanup_excel_file(example_name, zig_excel_file)
                
                return True
            else:
                f.write("RESULT: DIFFERENT - User reported visual differences\n")
                print("❌ Visual differences reported.")
                return False
    else:
        print(f"Screenshot not found at: {screenshot_file}")
        return False


def main():
    """Main function to create screenshots for Zig examples."""
    parser = argparse.ArgumentParser(description="Create screenshots for Zig examples")
    parser.add_argument("example", nargs="?", help="Example name to create screenshot for")
    parser.add_argument("--list", action="store_true", help="List examples without screenshots")
    parser.add_argument("--cleanup", action="store_true", help="Cleanup existing Zig Excel files in the project root")
    
    args = parser.parse_args()
    
    if args.cleanup:
        # Find all Zig Excel files in the project root
        root_dir = Path(__file__).parent.parent
        zig_excel_files = list(root_dir.glob("zig-*.xlsx")) + list(root_dir.glob("zig-*.xlsm"))
        
        if not zig_excel_files:
            print("No Zig Excel files found in the project root.")
            return 0
        
        print(f"Found {len(zig_excel_files)} Zig Excel files in the project root.")
        moved_count = 0
        
        for file_path in zig_excel_files:
            # Extract example name from filename (remove 'zig-' prefix and extension)
            example_name = file_path.stem[4:]  # Skip 'zig-' prefix
            
            if cleanup_excel_file(example_name, file_path):
                moved_count += 1
        
        print(f"Moved {moved_count} of {len(zig_excel_files)} files to the zig-output-xls directory.")
        return 0
    
    if args.list:
        missing = find_examples_without_screenshots()
        if missing:
            print("\nExamples without screenshots:")
            print(f"{'EXAMPLE':<25}")
            print("-" * 25)
            for example in missing:
                print(f"{example:<25}")
            print(f"\nTotal: {len(missing)} examples missing screenshots")
        else:
            print("All examples have screenshots!")
        return 0
    
    if not args.example:
        parser.print_help()
        return 1
    
    # Take screenshot
    print(f"\n=== Creating screenshot for {args.example} ===")
    success = take_screenshot(args.example)
    
    return 0 if success else 1


if __name__ == "__main__":
    sys.exit(main()) 