name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.10.0
      
      - name: build
        run: |
            sudo apt update && sudo apt install -y libxlsxwriter-dev;\
            zig build && zig build tutorial1; ls
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.10.0
      - run: |
            rm -rf zig-cache
            zig fmt --check --ast-check **.zig
