name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.10.0
      
      - name: build libxlsxwriter
        run: |
            sudo apt update && sudo apt install -y cmake git;\
            git clone https://github.com/jmcnamara/libxlsxwriter && cd libxlsxwriter; \
            CC="zig cc -fno-sanitize=all -lc $@" CXX="zig c++ -fno-sanitize=all -lc++ $@" \
            cmake -B build -H. -DCMAKE_BUILD_TYPE=Release;cmake --build build -j && sudo cmake --install build
      
      - name: build zig-examples
        run: |
            zig build && ls
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.10.0
      - run: |
            rm -rf zig-cache
            zig fmt --check --ast-check **.zig
